CREATE TABLE families (
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  name NVARCHAR(100) NOT NULL,
  code NVARCHAR(8) NOT NULL UNIQUE,
  created_at DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);

CREATE TABLE users (
  id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
  email NVARCHAR(255) NOT NULL UNIQUE,
  display_name NVARCHAR(100) NOT NULL,
  family_id UNIQUEIDENTIFIER REFERENCES families(id),
  created_at DATETIME2 NOT NULL DEFAULT GETUTCDATE()
);

CREATE TABLE otp_requests (
  email NVARCHAR(255) NOT NULL PRIMARY KEY,
  otp NVARCHAR(6) NOT NULL,
  expires_at DATETIME2 NOT NULL,
  attempts INT NOT NULL DEFAULT 0
);
